config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :skip => [:registrations]

  root 'home#index'
  resources :users, except: [:show, :destroy]
  resources :companies, except: [:show, :destroy]
  resources :departments, except: [:show, :destroy]
  resources :positions, except: [:show, :destroy]

end

app/models/department.rb
class Department < ActiveRecord::Base
  validates_uniqueness_of :name
end

app/controllers/departments_controller.rb
#encoding: utf-8
class DepartmentsController < ApplicationController
  load_and_authorize_resource

  def index
    @departments = @departments.page(params[:page])
  end

  def new
    
  end

  def create
    @department = Department.new(create_department_params)
    
    if @department.save
      redirect_to departments_url, :notice => "部门创建成功"
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    @department = Department.find_by_id(params[:id])

    if @department.update_attributes(update_department_params)
      redirect_to edit_department_path(@department), :notice => "部门更新成功"
    else
      render action: 'edit'
    end
  end

  private
  def create_department_params
    params.require(:department).permit(:name)
  end

  def update_department_params
    params.require(:department).permit(:name)
  end
end

app/views/departments/_form.html.erb
<% content_for :page_title do %>
<%= render "title_bar" %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box">
      <div class="portlet-body form">
        <!-- BEGIN FORM-->
        <%= form_for(@department, html: { class: "form-horizontal"}) do |f| %>
          <div class="form-body">
            <%= f.error_messages %>
            <h4 class="form-section">基本信息</h4>
            <div class="form-group">
              <%= render "shared/column_triple", :name => "名称", :content =>  f.c_text_field(:name) %>
            </div>
            
            <div class="form-actions right">
              <button type="submit" class="btn">保存</button>
            </div>
        <% end %>
        <!-- END FORM-->
      </div>
    </div>
  </div>
</div>

app/views/departments/_title_bar.html.erb
<h3 class="page-title">
部门管理 <small>部门管理</small>
</h3>
<ul class="page-breadcrumb breadcrumb">
  <li class="btn-group">
    <button type="button" class="btn grey dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" />
    <span>操作</span>
    <i class="fa fa-angle-down"></i>
    </button>
    <ul class="dropdown-menu pull-right" role="menu">
      <li><%= link_to "添加", new_department_path %></li>
    </ul>
  </li>
  <li>
    <i class="fa fa-home"></i>
    <%= link_to "Solar管理系统", root_path %>
    <i class="fa fa-angle-right"></i>
  </li>
  <li>
    <%= link_to "部门", departments_path %>
    <i class="fa fa-angle-right"></i>
  </li>
  <li>
    <%= page_title %>
  </li>
</ul>

app/views/departments/edit.html.erb
<%= render 'form' %>

app/views/departments/index.html.erb
<% content_for :page_title do %>
<%= render "title_bar" %>
<% end %>

<div class="row">
  <div class="col-md-12">
    <div class="portlet box">
      <div class="dataTables_wrapper form-inline" role="grid">
        <div class="row">
          <div class="col-md-12 col-sm-12">
          </div>
        </div>
        <div class="table-responsive">
          <table class="table table-striped table-bordered table-hover">
            <thead>
              <tr>
                <th>名称</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @departments.each do |item| %>
                <tr>
                  <td><%= item.name %></td>
                  <td>
                    <%= link_to '编辑', edit_department_path(item) %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= paginate @departments %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<%= render 'form' %>